'ci/cd':
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/workflows/**'

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'README.md'
              - '**/*.md'

tooling:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*TaskFile.yml'
              - '**/*Taskfile.yml'

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'test/**'
              - 'tests/**'

compute:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'components/ecoindex/compute/**'

scraper:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'components/ecoindex/scraper/**'

cli:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'bases/ecoindex/cli/**'

api:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'bases/ecoindex/backend/**'
              - 'bases/ecoindex/worker/**'

components:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'components/**'
