FROM python:3.12-slim AS requirements-stage

WORKDIR /tmp

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY pyproject.toml uv.lock projects/ecoindex_api/pyproject.toml ./
RUN uv export --package ecoindex_api --group worker --no-hashes --no-emit-workspace -o requirements.txt


FROM python:3.12-slim

ARG wheel=ecoindex_api-3.1.0-py3-none-any.whl

WORKDIR /code

# Needed for git repositories dependencies
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt 

COPY projects/ecoindex_api/dist/$wheel $wheel
RUN pip install --no-cache-dir $wheel
RUN pip install --no-cache-dir aiomysql asyncpg

RUN playwright install chromium --with-deps

RUN rm -rf $wheel requirements.txt /tmp/dist /var/lib/{apt,dpkg,cache,log}/

COPY projects/ecoindex_api/docker/worker/entrypoint.sh /usr/bin/entrypoint
COPY projects/ecoindex_api/scripts/start_rq_workers.sh /usr/bin/start_rq_workers.sh
COPY projects/ecoindex_api/scripts/clean_stale_rq_workers.py /usr/bin/clean_stale_rq_workers.py
RUN chmod +x /usr/bin/entrypoint /usr/bin/start_rq_workers.sh

ENTRYPOINT [ "/usr/bin/entrypoint" ]
