version: '3'

tasks:
  build:
    internal: true
    cmds:
      - |
        if docker buildx version > /dev/null 2>&1; then
          echo "docker buildx build --load -t vvatelot/ecoindex-{{.NAME}}:{{.VERSION}} -t vvatelot/ecoindex-{{.NAME}}:latest {{.OPTIONS}} ."
          docker buildx build --load -t vvatelot/ecoindex-{{.NAME}}:{{.VERSION}} -t vvatelot/ecoindex-{{.NAME}}:latest {{.OPTIONS}} .
        else
          echo "docker build -t vvatelot/ecoindex-{{.NAME}}:{{.VERSION}} -t vvatelot/ecoindex-{{.NAME}}:latest {{.OPTIONS}} ."
          docker build -t vvatelot/ecoindex-{{.NAME}}:{{.VERSION}} -t vvatelot/ecoindex-{{.NAME}}:latest {{.OPTIONS}} .
        fi
    silent: true
  
  push:
    internal: true
    cmds:
      - echo "docker push vvatelot/ecoindex-{{.NAME}}:{{.VERSION}}"
      - docker push vvatelot/ecoindex-{{.NAME}}:{{.VERSION}}
      - echo "docker push vvatelot/ecoindex-{{.NAME}}:latest"
      - docker push vvatelot/ecoindex-{{.NAME}}:latest
    silent: true
