version: '3'

tasks:
  tests:
    desc: Run tests
    cmds:
      - uv run pytest

  tests-coverage:
    desc: Run tests with coverage
    cmds:
      - uv run pytest --cov-report "xml:coverage.xml" --cov=. test
    
  tests-coverage-branch:
    desc: Run tests with coverage for current branch
    cmds:
      - uv run pytest --cov-report "xml:coverage.xml" --cov=. --picked --mode=branch test

  ty:
    desc: Run ty type checker
    cmds:
      - uv run ty check
  
  ruff:
    desc: Run ruff
    cmds:
      - uv run ruff check .
  
  quality-branch:
    desc: Run quality checks
    deps: [tests-coverage-branch, ty, ruff]
    cmds:
      - echo "Quality checks passed"

  default:
    desc: Run quality checks
    deps: [tests-coverage, ty, ruff]
    cmds:
      - echo "Quality checks passed"
