FROM python:3.12-slim

WORKDIR /code
ENV PYTHONPATH="/code"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY pyproject.toml uv.lock ./
COPY projects/ecoindex_scraper/ projects/ecoindex_scraper/
COPY bases/ bases/
COPY components/ components/

RUN uv sync --package ecoindex_scraper --frozen --no-dev --no-editable

ENV PATH="/code/.venv/bin:$PATH"

RUN uv run camoufox fetch

RUN rm -rf /tmp/dist /var/lib/{apt,dpkg,cache,log}/
