version: '3'

includes:
  uv:
    taskfile: ../../tasks/UvTaskfile.yml
    dir: ../..
  pypi:
    taskfile: ../../tasks/PypiTaskFile.yml
    dir: ../..

vars:
  PROJECT_NAME: scraper
  PACKAGE_NAME: ecoindex_scraper
  OUT_DIR: projects/ecoindex_scraper/dist

tasks:
  bump:
    desc: Bump the scraper version with rules:major, minor, patch, premajor, preminor, prepatch or prerelease.
    cmds:
      - task: uv:bump
        vars:
          VERSION_FILE_PATH: "components/ecoindex/scraper/VERSION"
          VERSION_RULE: "{{.CLI_ARGS}}"
    dir: ../..
    silent: true
