version: '3'

includes:
  uv:
    taskfile: ../../tasks/UvTaskfile.yml
    dir: ../..
  docker:
    taskfile: ../../tasks/DockerTaskfile.yml
    dir: ../..
  pypi:
    taskfile: ../../tasks/PypiTaskFile.yml
    dir: ../..

vars:
  PROJECT_NAME: cli
  PACKAGE_NAME: ecoindex_cli
  OUT_DIR: projects/ecoindex_cli/dist

tasks:
  bump:
    desc: Bump the CLI version with rules:major, minor, patch, premajor, preminor, prepatch or prerelease.
    cmds:
      - task: uv:bump
        vars:
          VERSION_FILE_PATH: "bases/ecoindex/cli/VERSION"
          VERSION_RULE: "{{.CLI_ARGS}}"
    dir: ../..
    silent: true
  
  docker-build:
    desc: Build the docker image
    deps: [uv:build]
    vars:
      VERSION:
        sh: cd ../.. && uv version --package ecoindex_cli --short
    cmds:
      - task: docker:build
        vars:
          VERSION: "{{.VERSION}}"
          NAME: "{{.PROJECT_NAME}}"
          OPTIONS: -f projects/ecoindex_cli/dockerfile --build-arg="wheel=ecoindex_cli-{{.VERSION}}-py3-none-any.whl"
    silent: true
  
  docker-push:
    desc: Push the docker image
    vars:
      VERSION:
        sh: cd ../.. && uv version --package ecoindex_cli --short
    cmds:
      - task: docker:push
        vars:
          VERSION: "{{.VERSION}}"
          NAME: "{{.PROJECT_NAME}}"
    silent: true
