name: Validate project quality

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  project-quality:
    name: Validate project quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Validate polylith project
        run: task project-check
      - name: Validate code quality
        run: task quality
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          title: Branch coverage
          badge-title: Coverage PR ${{ github.event.pull_request.number }}
          report-only-changed-files: true
