name: Update reference values
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: "♻️ Get last values from reference repository"
        run: |
          poetry run update-values
          poetry run black ./ecoindex/data
      - name: Update PR with new openapi version
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "⬆️ chore(values): Update reference values"
          branch: "chore/ecoindex-reference-values"
          path: "ecoindex/data/"
          commit-message: "⬆️ chore(values): Update reference values"
          auto-merge: squash
          body: "Update reference values from repository [cnumr/ecoindex_reference](https://www.github.com/cnumr/ecoindex_reference)"
